# -*- coding: utf-8 -*-
"""Regression_polynomiale.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t75uLRkaVPptjP8UjayB6FBPpOJHpcI3

# Regression Polynomiale

## Etape 1 : Chargement des Bibliothèques
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Etape 2 : Chargement des données"""

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
Y = dataset.iloc[:, -1].values

"""## Etape 3 : Entrainer le modèle de regression linéaire sur tout le dataset"""

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, Y)

"""## Etape 4 : Entrainer le modèle de regression polynomiale sur tout le dataset"""

from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)  # construction du modèle avec une puissance de 2
# création d'un objet X_poly qui contient la transformation du vecteur X
X_poly = poly_reg.fit_transform(X)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly, Y)       # on applique la regression linéaire

"""## Etape 5 : Visualisation des résultats du modèle linéaire"""

plt.scatter(X, Y, color = 'red')
plt.plot(X, lin_reg.predict(X), color = 'blue')
plt.title(' Vrai ou Faux (Regression linéaire)')
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.show()

"""## Etape 6 : Visualisation des résultats du modèle de regression polynomiale"""

plt.scatter(X, Y, color = 'red')
plt.plot(X, lin_reg_2.predict(X_poly), color = 'blue')
plt.title(' Vrai ou Faux (Regression polynomiale)')
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.show()

"""## Etape 7 : Visualition des résultats de la regression polynomiale (Pour une meilleure résolution et une courbe plus lisse)"""

x_grid = np.arange(min(X), max(X), 0.1) # on crée un tableau avec un pas de 0.1
x_grid = x_grid.reshape((len(x_grid), 1))
plt.scatter(X, Y, color = 'red')
plt.plot(x_grid, lin_reg_2.predict(poly_reg.fit_transform(x_grid)), color = 'blue')
plt.title(' Vrai ou Faux (Regression polynomiale)')
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.show()

"""## Etape 8 : Prédire un nouveau résultat d'une seule observation avec la regression linéaire """

lin_reg.predict([[6.5]])

"""## Etape 9 : Prédire un nouveau résultat d'une seule observation avec la regression polynomiale"""

lin_reg_2.predict(poly_reg.fit_transform([[6.5]]))